//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wad.iFollow.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public comment()
        {
            this.notifications = new HashSet<notification>();
        }
    
        public long id { get; set; }
        public long userId { get; set; }
        public long postId { get; set; }
        public string message { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
    
        public virtual post post { get; set; }
        public virtual user user { get; set; }
        public virtual ICollection<notification> notifications { get; set; }
    }
}
