//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wad.iFollow.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class follower
    {
        public long followedId { get; set; }
        public long followerId { get; set; }
        public Nullable<bool> isBlocked { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
