//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wad.iFollow.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class image
    {
        public image()
        {
            this.posts = new HashSet<post>();
        }
    
        public long id { get; set; }
        public string url { get; set; }
        public long ownerId { get; set; }
        public Nullable<bool> isAvatar { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual user user { get; set; }
        public virtual ICollection<post> posts { get; set; }
    }
}
