//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wad.iFollow.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class notification
    {
        public long id { get; set; }
        public long ownerId { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<float> rating { get; set; }
        public Nullable<long> commentId { get; set; }
        public Nullable<long> postId { get; set; }
        public long userId { get; set; }
        public bool IsRead { get; set; }
        public virtual comment comment { get; set; }
        public virtual user user { get; set; }
        public virtual post post { get; set; }
        public virtual user user1 { get; set; }
    }
}
