//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wad.iFollow.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.comments = new HashSet<comment>();
            this.emails = new HashSet<email>();
            this.followers = new HashSet<follower>();
            this.followers1 = new HashSet<follower>();
            this.images = new HashSet<image>();
            this.notifications = new HashSet<notification>();
            this.notifications1 = new HashSet<notification>();
            this.posts = new HashSet<post>();
            this.ratings = new HashSet<rating>();
            this.posts1 = new HashSet<post>();
        }
    
        public long id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string confirmationKey { get; set; }
        public Nullable<System.DateTime> registrationDate { get; set; }
        public string country { get; set; }
        public string city { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public Nullable<bool> isConfirmed { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<bool> enabledNotif { get; set; }
    
        public virtual ICollection<comment> comments { get; set; }
        public virtual ICollection<email> emails { get; set; }
        public virtual ICollection<follower> followers { get; set; }
        public virtual ICollection<follower> followers1 { get; set; }
        public virtual ICollection<image> images { get; set; }
        public virtual ICollection<notification> notifications { get; set; }
        public virtual ICollection<notification> notifications1 { get; set; }
        public virtual ICollection<post> posts { get; set; }
        public virtual ICollection<rating> ratings { get; set; }
        public virtual ICollection<post> posts1 { get; set; }
    }
}
